### ISSUE TITLE
Planeación del prototipo avión No. 1

### ISSUE THREAD

**Issue by amelissagomez** [ISWPOLI/scrum-vs-psp-scrum-psp#18]
**Planeación del prototipo avión No. 1**
Estimación de tiempo para la planeación del prototipo.

**Tareas**
- [x] Estimación tiempos para la ejecución del diseño
- [x] Asignación de tareas

**Comment by Lakes1234** [comment]
**Planeación del prototipo avión No. 1**

Estimación tiempos para la ejecución del diseño

- [x] Construcción del primer prototipo 15 min.

- [x] Documentación primer prototipo 1 hora

 - [x] Visualización del modelo primer prototipo 8 min.

**Asignación**

- [x] Construcción primer prototipo avivo Andres

- [x] Documentación Christian y Steven
