### ISSUE TITLE
Planeacion

### ISSUE THREAD

**Issue by alejandro995** [ISWPOLI/scrum-vs-psp-scrum-psp#34]
- [x] Estimación de tiempos @Basespoli 
- [x] Levantamiento de Requerimientos @buitrago001
- [ ] Construcción de Back-log @alejandro995 
- [ ] Historias de usuario @alejandro995 
- [ ] release mapping @sebasc91

**Comment by ghost** [comment]
Se reporta la documentación de la Planeación donde se especifico los sprints a desarrollar por cada integrante del grupo.
[PLaneación.docx](https://github.com/ISWPOLI/scrum-vs-psp-scrum-psp/files/832793/PLaneacion.docx)

**Comment by buitrago001** [comment]
Se agregan requerimientos en documento requerimiento aviones de papel posteado en el repositorio
https://drive.google.com/drive/folders/0B3Uf6CJULz0SaWJCMkhkS1FBVGc

**Comment by ghost** [comment]
Requerimientos primera planeación 
https://docs.google.com/spreadsheets/d/1K2Qki2NmSyHtKlymF-PsqcIMgcbDR7JPyZ61JgVGyEs/edit?usp=sharing
