### ISSUE TITLE
Construccion de Modelo Royal

### ISSUE THREAD

**Issue by sebasc91** [ISWPOLI/scrum-vs-psp-scrum-psp#36]
Rol: Como operador
Característica / Funcionalidad: Necesitor seguir las instrucciones para la contruccion del avion y resgistro de tiempos.
Razon/ Resultado: Con el fin tener el producto finalizado para revision.

- [x] Ver el Video
- [x] Hacer pliegues.
- [x] Registro de Tiempo

**Comment by buitrago001** [comment]
Se completa las tareas de manera simultanea llevando un tiempo de 17 minutos en finalizar la construccion del modelo royal 1
