### ISSUE TITLE
Construcción Modelo Generación 1

### ISSUE THREAD

**Issue by sebasc91** [ISWPOLI/scrum-vs-psp-scrum-psp#38]
Rol: Como operador
Característica / Funcionalidad: Necesitor seguir las instrucciones para la contruccion del avion y resgistro de tiempos.
Razon/ Resultado: Con el fin tener el producto finalizado para revision.

- [x] Ver el Video 
- [x] Hacer pliegues
- [x] Registro de Tiempo

**Comment by buitrago001** [comment]
Se lleva a cabo la construcción del modelo de manera simultanea mientras se sigue las instrucciones, se completa la construcción de la primera versión en un tiempo estimado de 7 minutos
