### ISSUE TITLE
Construcción Avión de Papel

### ISSUE THREAD

**Issue by alejandro995** [ISWPOLI/scrum-vs-psp-scrum-psp#7]

**Comment by ghost** [comment]
[Analisis PSP y tiempos aviones de papel.xlsx](https://github.com/ISWPOLI/scrum-vs-psp-scrum-psp/files/832901/Analisis.PSP.y.tiempos.aviones.de.papel.xlsx)

**Comment by ghost** [comment]
Ficha psp
https://docs.google.com/spreadsheets/d/1IiFiBIccQpqEJsSnvhuVRIbKQezAUJkAHlmkdtziFdw/edit#gid=555909140
